# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mofre' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mofre
  pod 'MVPArchitecture', :path => '../'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Swinject'

  target 'MofreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
