# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Mofre' do
  # Pods for Mofre
  pod 'MVPArchitecture', :path => '../'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Swinject'

  target 'MofreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Controller' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Swinject'
end
